const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const ROOT = __dirname, PORT = process.env.PORT || 3001;
const DATA_DIR = process.env.VERCEL ? '/tmp' : path.join(ROOT, 'data'), DATA_FILE = path.join(DATA_DIR, 'wallet.json');
const sessions = new Map();
const initialData = { users: [{ id: 'user_1', name: 'Ranjitha', email: 'ranjit@example.com', password: 'wallet123', balance: 48240.5, monthlyBudget: 30000, cards: [{ id: 'card_1', brand: 'VISA', last4: '9016', expiry: '08/28', gradient: true }, { id: 'card_2', brand: 'mastercard', last4: '3048', expiry: '11/27', gradient: false }] }], transactions: [{ id: 'tx_1', userId: 'user_1', merchant: 'Netflix', category: 'Entertainment', amount: -649, date: '2026-08-28T04:12:00.000Z', icon: 'N' }, { id: 'tx_2', userId: 'user_1', merchant: 'Salary credit', category: 'Income', amount: 52000, date: '2026-08-27T04:45:00.000Z', icon: 'S' }, { id: 'tx_3', userId: 'user_1', merchant: 'Third Wave Coffee', category: 'Food & drinks', amount: -320.5, date: '2026-08-27T10:48:00.000Z', icon: '☕' }, { id: 'tx_4', userId: 'user_1', merchant: 'To Maya Sharma', category: 'Transfer', amount: -2500, date: '2026-08-26T12:32:00.000Z', icon: '↗' }] };
function readData() { if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR); if (!fs.existsSync(DATA_FILE)) fs.writeFileSync(DATA_FILE, JSON.stringify(initialData, null, 2)); return JSON.parse(fs.readFileSync(DATA_FILE, 'utf8')); }
function writeData(data) { fs.writeFileSync(DATA_FILE, JSON.stringify(data, null, 2)); }
function json(res, status, body) { res.writeHead(status, { 'Content-Type': 'application/json' }); res.end(JSON.stringify(body)); }
function body(req) { return new Promise((resolve, reject) => { let value = ''; req.on('data', chunk => value += chunk); req.on('end', () => { try { resolve(value ? JSON.parse(value) : {}); } catch { reject(new Error('Invalid JSON body')); } }); }); }
function safeUser(user) { const { password, ...safe } = user; return safe; }
function activeUser(req, data) { const token = (req.headers.authorization || '').replace(/^Bearer\s+/i, ''); return data.users.find(user => user.id === sessions.get(token)); }
function protectedUser(req, res, data) { const user = activeUser(req, data); if (!user) json(res, 401, { error: 'Please sign in first.' }); return user; }
function summary(user, all) { const transactions = all.filter(tx => tx.userId === user.id); const spent = transactions.filter(tx => tx.amount < 0).reduce((total, tx) => total + Math.abs(tx.amount), 0); return { user: safeUser(user), balance: user.balance, spent, remaining: Math.max(0, user.monthlyBudget - spent) }; }
function serve(res, urlPath) { const relative = urlPath === '/' ? 'index.html' : urlPath.slice(1); const candidates = [path.resolve(ROOT, relative), path.resolve(ROOT, 'public', relative)]; const file = candidates.find(candidate => candidate.startsWith(ROOT) && fs.existsSync(candidate) && !fs.statSync(candidate).isDirectory()); if (!file) return false; const types = { '.html': 'text/html', '.css': 'text/css', '.js': 'application/javascript' }; res.writeHead(200, { 'Content-Type': types[path.extname(file)] || 'application/octet-stream' }); fs.createReadStream(file).pipe(res); return true; }

async function handler(req, res) {
  const url = new URL(req.url, `http://${req.headers.host}`);
  try {
    if (req.method === 'POST' && url.pathname === '/api/auth/login') { const { email, password } = await body(req); const data = readData(); const user = data.users.find(item => item.email.toLowerCase() === String(email).toLowerCase() && item.password === password); if (!user) return json(res, 401, { error: 'Invalid email or password.' }); const token = crypto.randomUUID(); sessions.set(token, user.id); return json(res, 200, { token, user: safeUser(user) }); }
    const data = readData(); const user = url.pathname.startsWith('/api/') ? protectedUser(req, res, data) : null; if (url.pathname.startsWith('/api/') && !user) return;
    if (req.method === 'GET' && url.pathname === '/api/summary') return json(res, 200, summary(user, data.transactions));
    if (req.method === 'GET' && url.pathname === '/api/transactions') return json(res, 200, data.transactions.filter(tx => tx.userId === user.id).sort((a,b) => new Date(b.date) - new Date(a.date)));
    if (req.method === 'POST' && url.pathname === '/api/add-money') { const { amount } = await body(req); const value = Number(amount); if (!(value > 0)) return json(res, 400, { error: 'Enter a valid amount.' }); user.balance = Number((user.balance + value).toFixed(2)); const tx = { id: crypto.randomUUID(), userId: user.id, merchant: 'Added money', category: 'Income', amount: value, date: new Date().toISOString(), icon: '+' }; data.transactions.push(tx); writeData(data); return json(res, 201, { transaction: tx }); }
    if (req.method === 'POST' && url.pathname === '/api/withdraw') { const { amount, account = 'Bank account' } = await body(req); const value = Number(amount); if (!(value > 0)) return json(res, 400, { error: 'Enter a valid amount.' }); if (value > user.balance) return json(res, 400, { error: 'Insufficient balance.' }); user.balance = Number((user.balance - value).toFixed(2)); const tx = { id: crypto.randomUUID(), userId: user.id, merchant: `Withdrawal to ${account}`, category: 'Withdrawal', amount: -value, date: new Date().toISOString(), icon: '⇧' }; data.transactions.push(tx); writeData(data); return json(res, 201, { transaction: tx }); }
    if (req.method === 'POST' && url.pathname === '/api/transfers') { const { recipient, amount, note = '' } = await body(req); const value = Number(amount); if (!recipient || !(value > 0)) return json(res, 400, { error: 'Enter a recipient and valid amount.' }); if (value > user.balance) return json(res, 400, { error: 'Insufficient balance.' }); user.balance = Number((user.balance - value).toFixed(2)); const tx = { id: crypto.randomUUID(), userId: user.id, merchant: `To ${recipient}`, category: 'Transfer', amount: -value, note, date: new Date().toISOString(), icon: '↗' }; data.transactions.push(tx); writeData(data); return json(res, 201, { transaction: tx }); }
    if (req.method === 'POST' && url.pathname === '/api/requests') { const { contact, amount, note = '' } = await body(req); const value = Number(amount); if (!contact || !(value > 0)) return json(res, 400, { error: 'Enter a contact and valid amount.' }); const tx = { id: crypto.randomUUID(), userId: user.id, merchant: `Requested from ${contact}`, category: 'Payment request', amount: 0, requestedAmount: value, note, status: 'Pending', date: new Date().toISOString(), icon: '↓' }; data.transactions.push(tx); writeData(data); return json(res, 201, { request: tx }); }
    if (req.method === 'POST' && url.pathname === '/api/bills') { const { biller, amount } = await body(req); const value = Number(amount); if (!biller || !(value > 0)) return json(res, 400, { error: 'Enter a biller and valid amount.' }); if (value > user.balance) return json(res, 400, { error: 'Insufficient balance.' }); user.balance = Number((user.balance - value).toFixed(2)); const tx = { id: crypto.randomUUID(), userId: user.id, merchant: `${biller} bill`, category: 'Bills', amount: -value, date: new Date().toISOString(), icon: '▤' }; data.transactions.push(tx); writeData(data); return json(res, 201, { transaction: tx }); }
    if (req.method === 'POST' && url.pathname === '/api/scan-pay') { const { merchant, amount } = await body(req); const value = Number(amount); if (!merchant || !(value > 0)) return json(res, 400, { error: 'Enter the merchant and a valid amount.' }); if (value > user.balance) return json(res, 400, { error: 'Insufficient balance.' }); user.balance = Number((user.balance - value).toFixed(2)); const tx = { id: crypto.randomUUID(), userId: user.id, merchant, category: 'Scan & pay', amount: -value, date: new Date().toISOString(), icon: '⌘' }; data.transactions.push(tx); writeData(data); return json(res, 201, { transaction: tx }); }
    if (req.method === 'POST' && url.pathname === '/api/cards') { const { brand = 'VISA', last4, expiry } = await body(req); if (!/^\d{4}$/.test(String(last4)) || !/^\d{2}\/\d{2}$/.test(String(expiry))) return json(res, 400, { error: 'Enter last 4 digits and an MM/YY expiry.' }); const card = { id: crypto.randomUUID(), brand, last4: String(last4), expiry, gradient: user.cards.length % 2 === 0 }; user.cards.push(card); writeData(data); return json(res, 201, card); }
    if (!url.pathname.startsWith('/api/') && serve(res, url.pathname)) return; json(res, 404, { error: 'Not found.' });
  } catch (error) { json(res, 500, { error: error.message || 'Server error.' }); }
}

if (require.main === module) {
  http.createServer(handler).listen(PORT, () => console.log(`Pulse Wallet running at http://localhost:${PORT}`));
}

module.exports = handler;
